apiVersion: v1
kind: Secret
metadata:
  name: font-scanner-secrets
  namespace: font-scanner
  labels:
    app: font-scanner
type: Opaque
stringData:
  # Add your secret values here
  # Example: API_KEY: "your-api-key-here"
  # These should be injected via CI/CD or sealed-secrets in production
  PLACEHOLDER: "replace-with-actual-secrets"
